spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/skillbook
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_KEY}
  expirationMs: 1800000

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: health, info
