spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbook
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Development configuration
cors:
  allowed-origins: http://localhost:3000

# Logging configuration for development
logging:
  level:
    root: INFO
    com.skillbook: DEBUG
    org.springframework.security: DEBUG
