name: Skillbook CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    name: Build, Test, and Push to ECR
    runs-on: ubuntu-latest

    env:
      # Environment variables for Spring (if you switch to env vars)
      API_KEY: ${{ secrets.API_KEY }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Inject secrets.properties (if not using env vars)
        run: |
          echo "api.key=${{ secrets.API_KEY }}" >> src/main/resources/secrets.properties
          echo "db.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/secrets.properties

      - name: Lint Java Code (optional)
        run: mvn checkstyle:check

      - name: Run Tests with Coverage
        run: mvn clean verify

      - name: Run OWASP Dependency Check (security scan)
        run: mvn org.owasp:dependency-check-maven:check

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/skillbook-api:latest .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/skillbook-api:latest
